print("How old are you?", end=" ")
age = int(input())
print("How tall are you?", end=" ")
height = float(input())
print("How much do you weigh?", end=" ")
weight = float(input())
print(f"So, you're {age} old, {height} tall and {weight} heavy.")
