# Atividade 3
import turtle

turtle.colormode(255)
tartaruga = turtle.Turtle()
espaco = 30
tartaruga.shape("turtle")
tartaruga.color(255, 0, 0)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(255, 127, 0)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(255, 255, 0)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(0, 255, 0)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(0, 0, 255)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(75, 0, 130)
tartaruga.stamp()
tartaruga.penup()
tartaruga.forward(espaco)
tartaruga.pendown()
tartaruga.color(148, 0, 211)
input()
