import turtle

tartaruga = turtle.Turtle()
tartaruga.penup()
tartaruga.color("yellow")
tartaruga.forward(50)
tartaruga.pendown()
tartaruga.right(90)
tartaruga.forward(50)
tartaruga.right(90)
tartaruga.forward(100)
tartaruga.right(90)
tartaruga.forward(100)
tartaruga.right(90)
tartaruga.forward(100)
tartaruga.right(90)
tartaruga.forward(50)
tartaruga.left(180)
tartaruga.forward(50)
tartaruga.color("red")
tartaruga.left(45)
tartaruga.forward(70.71)
tartaruga.left(90)
tartaruga.forward(70.71)
tartaruga.penup()
tartaruga.goto(0, 0)
tartaruga.color("green")
tartaruga.shape("turtle")
tartaruga.right(135)
input()
# quadrado 100 x 100
